### ISSUE TITLE
Importing multiple frames with uneven bounding boxes always end up off-center in the latest release

### ISSUE THREAD

**Issue by AhriCutii** [neivv/animosity#3]
I have a bunch of frames from a render that I've been trying for hours to import without them ending up off-center. If I immediately export them after importing I see that they are either put in the top-left or bottom-right of an image that is like 2 times bigger than the original size no matter how I try to resize the frames and ingame they are way offcenter. 
It would be helpful if the program would always put the imports in the center of the final image instead of the top-left/bottom-right. I assume its because the bounding boxes of each frame have very uneven sizes, which I don't have any control over.

Here's the frames Im trying to import
https://mega.nz/file/heUBkJ5D#oT2iDthAU1GbBuIBqBfSJrQ1ux-yHpQwmFCi-7XyUMM

**Comment by AhriCutii** [comment]
More info I just noticed: This happens even with blizz frames, not just mine. I tried importing the high templar frames into my unit and they're also completely off center. This is the result https://imgur.com/a/fPTi7Am (in this pic, my archer frames replace the marine's). Notice how off they are from the selection circles. 
Strangely the custom grp frames created by animosity used for selection pixels usually are properly centered on the unit.

Edit:
Alright, final update:
I switched to release version 0.5.4 and the frames are now finally being imported correctly https://imgur.com/a/1XtQ1oT . This seems to only be a issuewith the latest release version.
Well, it isnt perfect, it looks like the frames are a bit too low. notice how the selection circle is in the center of the unit instead of are their feet. But at least the unit is usable now.
Edit 2:
Im stupid I closed the issue on accident

**Comment by neivv** [comment]
I think this is caused by the fact that animosity, other than v 0.5.4, doesn't set sprite dimensions on import and you'd have to set them manually to the input image bounds. Obviously doing it automatically would be ideal, but when I added that in 0.5.4 I got quickly a report that it broke some imports that used to work.. So it got reverted and I hadn't looked at it since then. 
I'll take another look on how to enable it without breaking whatever it used to break...

The sprite is placed bit low in game since the unit is bit placed bit low in the input frames.
Either center the unit differently in the input frames, or adjust control selection circle position in sprites.dat, also probably have to adjust unit dimensions in units.dat.

Also FWIW if you run into issues with SD imports getting centered incorrectly anyway, it may be fixable by manually writing the dimensions for the SD sprite that are usually 0/0. Or alternatively importing SD only with .json edited to have `"frame_type": 0`. SD centering is something I didn't understand that well last time I worked on animosity so it makes some wrong assumptions there.

Edit: I tried importing the frames myself, (setting manually dimensions 635x635 for HD/HD2 and 158x158 for SD) and I didn't have issue with the selection circle being too high, so idk then what's up with that.

**Comment by AhriCutii** [comment]
I figured what the issue was. It was all on my end.
I didn't know that you had to manually type the dimensions on every import. 0.5.4 was the first version I used.
But the thing that really messed my imports up was that even when I did type the dimensions manually, I thought that HD2 dimensions are supposed to be half the size of HD dimensions. And I mostly use HD2 graphics ingame so yeah. I wouldnt have figured that one out if I hadn't seen your comment.
I suppose it would help if the program automatically made HD and HD2 dimensions the same(unless there is a scenario where you'd want them to be different)
And the selection circle thing I fixed by changing some settings in sprites.dat
I think I can finally close the issue now.
